version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "88:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3339:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: